darknetConfigFile: /home/ubuntu/go/src/github.com/ChengWu-NJ/yolosvc/bin/yolosvc/darknetfiles/nn.cfg
objNamesFile: /home/ubuntu/go/src/github.com/ChengWu-NJ/yolosvc/bin/yolosvc/darknetfiles/obj.names
darknetWeightsFile: /home/ubuntu/go/src/github.com/ChengWu-NJ/yolosvc/bin/yolosvc/darknetfiles/nn.weights
detectThreshold: 0.8
portOfGrpcSvc: 37658
objClasses:
- id: 0
  name: yellowGourami
  labelColorR: 237
  labelColorG: 17
  labelColorB: 237
- id: 1
  name: blueGourami
  labelColorR: 141
  labelColorG: 17
  labelColorB: 113
- id: 2
  name: redFighter
  labelColorR: 237
  labelColorG: 45
  labelColorB: 209
- id: 3
  name: originalFighter
  labelColorR: 86
  labelColorG: 237
  labelColorB: 168
- id: 4
  name: fox
  labelColorR: 72
  labelColorG: 182
  labelColorB: 237
- id: 5
  name: sucker
  labelColorR: 237
  labelColorG: 196
  labelColorB: 58
- id: 6
  name: tiger
  labelColorR: 154
  labelColorG: 100
  labelColorB: 17
- id: 7
  name: WCMM
  labelColorR: 223
  labelColorG: 31
  labelColorB: 237
